[Draft]Migration: pydot to ghaphviz
scikit-hep/decaylanguage pull request #119
Opened 2021-01-01 12:30 UTC by Bhanu-mbvg

Fixes Issue #105

2021-01-04 12:33 UTC, eduardo-rodrigues commented
Thank you for this PR, @Bhanu-mbvg. Do not forget to update the tests accordingly, and to remove any reference to `pydot` across all files.

2021-01-04 13:54 UTC, Bhanu-mbvg commented
Hey @eduardo-rodrigues yes I'll work on changing tests as well.

2021-01-05 15:23 UTC, eduardo-rodrigues requested changes
The replacement of `pydot.dot` with graphviz's `render` cannot be the full story. You need to look at the attributes/properties we want to deal with an provide a proper replacement. I'm happy that the tests I wrote actually catch various issues here :-).

2021-01-05 15:23 UTC, eduardo-rodrigues commented on environment.yml
> -  - pydot>=1.3.0
You should instead replace with `graphviz` because we definitely want to have it available e.g. in Binder launches of the demo notebook.

2021-01-13 12:29 UTC, eduardo-rodrigues commented
How are you getting along with the missing bits, @Bhanu-mbvg?

2021-01-29 11:06 UTC, eduardo-rodrigues commented
Hi @Bhanu-mbvg, any update? Are you stuck and need help?

2021-02-22 17:07 UTC, eduardo-rodrigues commented
OK @Bhanu-mbvg, that's a shame but at this point I assume you won't finish this task. I will try and get to it soon myself. Thanks anyway.

2021-03-23 12:07 UTC, eduardo-rodrigues commented
Last ping @bhanu-mbvg - will you or will you not try and finalise this enhancement?

2021-03-23 16:48 UTC, closed without merging